project:
  type: website

website:
  title: "Cheshtaa Chitkara"

  navbar:
    background: light
    left:
      - href: index.qmd
        text: Home

      - href: about.qmd
        text: About

      - href: research.qmd
        text: Research

      - href: featured.qmd
        text: Featured

      - href: teaching.qmd
        text: Teaching

      - href: cv.qmd
        text: CV

      - href: news.qmd
        text: News

      - href: contact.qmd
        text: Contact

format:
  html:
    theme:
      - flatly
    css: styles.css
    toc: false
    page-layout: full
    smooth-scroll: true